### ISSUE TITLE
[pIChemSt] Readme install instructions not working

### ISSUE THREAD

**Issue by adam-of-barot** [AstraZeneca/peptide-tools#2]
I tried installing pIChemSt as stated in the readme, but I could not get it to work that way.

The following method seemed to work:
```bash
# Optional: create virtual environment for project
python -m venv ~/venv/peptide-tools
source ~/venv/peptide-tools/bin/activate
# Install packages
python setup.py install
# Configure shell
sh setup.cli
```

`setup.cli` leaves a lingering "-e" line in .bashrc, but otherwise `pichemist` is installed and is now usable.

**Comment by ghiander** [comment]
Hello @adam-of-barot, 

We pushed a fix for installing pichemist. Please refer to the new instructions.

Giammy
